search_id: Int32
search_timestamp: Datetime
expedia_site_id: Int16
user_country_id: Int16
user_hist_avg_stars: Float32
user_hist_avg_price: Float32
hotel_country_id: Int16
hotel_id: Int32
hotel_star_rating: Float32
hotel_review_score: Float32
is_chain_hotel: UInt8
location_score_primary: Float32
location_score_secondary: Float32
log_historical_price: Float32
display_position: Int16
display_price: Float32
has_promotion: UInt8
destination_id: Int32
stay_duration: Int16
days_until_checkin: Int16
num_adults: Int8
num_children: Int8
num_rooms: Int8
includes_saturday_night: UInt8
query_hotel_affinity_log: Float32
orig_destination_distance: Float32
query_was_randomized: UInt8
comp1_rate: Int8
comp1_inv: Int8
comp1_rate_percent_diff: Float32
comp2_rate: Int8
comp2_inv: Int8
comp2_rate_percent_diff: Float32
comp3_rate: Int8
comp3_inv: Int8
comp3_rate_percent_diff: Float32
comp4_rate: Int8
comp4_inv: Int8
comp4_rate_percent_diff: Float32
comp5_rate: Int8
comp5_inv: Int8
comp5_rate_percent_diff: Float32
comp6_rate: Int8
comp6_inv: Int8
comp6_rate_percent_diff: Float32
comp7_rate: Int8
comp7_inv: Int8
comp7_rate_percent_diff: Float32
comp8_rate: Int8
comp8_inv: Int8
comp8_rate_percent_diff: Float32
was_clicked: UInt8
booking_cost: Float32
was_booked: UInt8
