
theme:
  background_color: "#ffffff"
  sidebar_background: "#f8f9fa"
  page_padding: "30px"
  page_margin: "20px"
  border_radius: "10px"
  box_shadow: "0px 4px 8px rgba(0, 0, 0, 0.05)"

sidebar:
  title_font_size: "22px"
  title_font_family: "Open Sans, sans-serif"
  nav_font_size: "16px"

datatable:
  header_background: "#e1e5eb"
  cell_font_family: "Open Sans, sans-serif"
  cell_font_size: "14px"
  header_font_size: "15px"
  cell_padding: "10px"
